name: Run Maven Tests on Windows with Chrome and Java 17

on:
  push:
    branches:
      - master  # Trigger on push to the master branch
  pull_request:
    branches:
      - master  # Trigger on pull requests targeting the master branch

jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3  # Fetch the repository code

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'  # Specify Java 17
        distribution: 'temurin'  # Use the Temurin distribution of Java

    - name: Cache Maven Dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2  # Cache Maven dependencies
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Run Tests
      run: mvn test
